### ISSUE TITLE
Export Specific Settings

### ISSUE THREAD

**Issue by NTWKMAN** [silaslenz/slic3rpe-profile#1]
Hello,

I was searching how people organize their slic3rPE profiles, yours is really good.

Question, how do you get slic3rPE to export your specific printer, print and filament settings? Do you edit each config file by hand? When I export, not bundle export, I get all three configs rolled into one ini. Sorry for opening an issue, I did the standard web search first and didn't come up with anything.

Thanks!

**Comment by silaslenz** [comment]
Hi,

that is the structure that Slic3r uses in its config directory (~/.Slic3rPE on Linux), so I simply initialized the git repo there and added the wanted files. Also has the benefit if not needing to import/export when commiting/reverting/setting up a new computer etc.

Minor warning: if you use octoprint the api key will be in the printer profile. Should be fine as long as it's not remotely accessible (which it shouldn't be anyways), but worth noting.

**Comment by NTWKMAN** [comment]
Ahh, very cool. On Windows that's %AppData%\Roaming\Slic3rPE should anyone find this and use that platform. That's very helpful, thank you.

Thanks for the warning, I have been removing the api key and address manually. My octoprint server is local only, as it should be.

Thanks again, cheers!
